name: Force close unauthorized writer's issue
on:
  issues:
    types: [opened]
jobs:
  close-issue:
    runs-on: ubuntu-latest
    steps:
      - #if: github.event.issue.user.login != github.repository_owner
        name: Close Issue
        run: gh issue delete  ${{ github.event.issue.number }} -R ${{ OWNER }}/${{ REPO }} --yes
        env:
          GH_TOKEN: ${{ github.token }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
