name: Force close unauthorized writer's issue
on:
  issues:
    types: [opened]
jobs:
  close-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - #if: github.event.issue.user.login != github.repository_owner
        name: Close Issue
        run: gh issue delete $NUMBER --yes #-R $OWNER/$REPO --yes
        env:
          GH_TOKEN: ${{ secrets.ISSUE_CLOSE_TOKEN }} # admin role for delete
          NUMBER: ${{ github.event.issue.number }}
          GH_REPO: ${{ github.repository }}
          #OWNER: ${{ github.repository_owner }}
          #REPO: ${{ github.event.repository.name }}
